bootcamp/news/urls.py
from django.conf.urls import url

from bootcamp.news import views

app_name = 'news'
urlpatterns = [
    url(r'^$', views.NewsListView.as_view(), name='list'),
    url(r'^delete/(?P<pk>[-\w]+)/$',
        views.NewsDeleteView.as_view(), name='delete_news'),
    url(r'^post-news/$', views.post_news, name='post_news'),
    url(r'^like/$', views.like, name='like_post'),
    url(r'^dislike/$', views.dislike, name='dislike_post'),
    url(r'^get-thread/$', views.get_thread, name='get_thread'),
    url(r'^post-comment/$', views.post_comment, name='post_comments'),
    url(r'^update-interactions/$', views.update_interactions, name='update_interactions'),
    url(r'^news-table/$', views.tablify, name='tablify'),
]

bootcamp/qa/urls.py
from django.conf.urls import url

from bootcamp.qa import views

app_name = 'qa'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='question_main'),
    url(r'^main/$', views.FakeIndexView.as_view(), name='question_fake_main'),
    url(r'^question-list/$', views.QuestionListView.as_view(), name='index_noans'),
    url(r'^question-list-2/$', views.Question2ListView.as_view(), name='index_noans2'),
    url(r'^question-list-3/$', views.Question3ListView.as_view(), name='index_noans3'),
    url(r'^question-list-4/$', views.Question4ListView.as_view(), name='index_noans4'),
    url(r'^question-list-5/$', views.Question5ListView.as_view(), name='index_noans5'),
    url(r'^question-list-6/$', views.Question6ListView.as_view(), name='index_noans6'),
    url(r'^question-list-7/$', views.Question7ListView.as_view(), name='index_noans7'),
    url(r'^question-list-8/$', views.Question8ListView.as_view(), name='index_noans8'),
    url(r'^answered/$', views.QuestionAnsListView.as_view(), name='index_ans'),
    url(r'^answered-2/$', views.Question2AnsListView.as_view(), name='index_ans2'),
    url(r'^answered-3/$', views.Question3AnsListView.as_view(), name='index_ans3'),
    url(r'^answered-4/$', views.Question4AnsListView.as_view(), name='index_ans4'),
    url(r'^answered-5/$', views.Question5AnsListView.as_view(), name='index_ans5'),
    url(r'^answered-6/$', views.Question6AnsListView.as_view(), name='index_ans6'),
    url(r'^answered-7/$', views.Question7AnsListView.as_view(), name='index_ans7'),
    url(r'^answered-8/$', views.Question8AnsListView.as_view(), name='index_ans8'),
    url(r'^indexed/$', views.QuestionsIndexListView.as_view(), name='index_all'),
    url(r'^indexed-2/$', views.Questions2IndexListView.as_view(), name='index_all2'),
    url(r'^indexed-3/$', views.Questions3IndexListView.as_view(), name='index_all3'),
    url(r'^indexed-4/$', views.Questions4IndexListView.as_view(), name='index_all4'),
    url(r'^indexed-5/$', views.Questions5IndexListView.as_view(), name='index_all5'),
    url(r'^indexed-6/$', views.Questions6IndexListView.as_view(), name='index_all6'),
    url(r'^indexed-7/$', views.Questions7IndexListView.as_view(), name='index_all7'),
    url(r'^indexed-8/$', views.Questions8IndexListView.as_view(), name='index_all8'),
    url(r'^question-detail/(?P<pk>\d+)/$', views.QuestionDetailView.as_view(), name='question_detail'),
    url(r'^question-detail-2/(?P<pk>\d+)/$', views.Question2DetailView.as_view(), name='question_detail2'),
    url(r'^question-detail-3/(?P<pk>\d+)/$', views.Question3DetailView.as_view(), name='question_detail3'),
    url(r'^question-detail-4/(?P<pk>\d+)/$', views.Question4DetailView.as_view(), name='question_detail4'),
    url(r'^question-detail-5/(?P<pk>\d+)/$', views.Question5DetailView.as_view(), name='question_detail5'),
    url(r'^question-detail-6/(?P<pk>\d+)/$', views.Question6DetailView.as_view(), name='question_detail6'),
    url(r'^question-detail-7/(?P<pk>\d+)/$', views.Question7DetailView.as_view(), name='question_detail7'),
    url(r'^question-detail-8/(?P<pk>\d+)/$', views.Question8DetailView.as_view(), name='question_detail8'),
    url(r'^ask-question/$', views.CreateQuestionView.as_view(), name='ask_question'),
    url(r'^ask-question-2/$', views.CreateQuestion2View.as_view(), name='ask_question2'),
    url(r'^ask-question-3/$', views.CreateQuestion3View.as_view(), name='ask_question3'),
    url(r'^ask-question-4/$', views.CreateQuestion4View.as_view(), name='ask_question4'),
    url(r'^ask-question-5/$', views.CreateQuestion5View.as_view(), name='ask_question5'),
    url(r'^ask-question-6/$', views.CreateQuestion6View.as_view(), name='ask_question6'),
    url(r'^ask-question-7/$', views.CreateQuestion7View.as_view(), name='ask_question7'),
    url(r'^ask-question-8/$', views.CreateQuestion8View.as_view(), name='ask_question8'),
    url(r'^propose-answer/(?P<question_id>\d+)/$', views.CreateAnswerView.as_view(), name='propose_answer'),
    url(r'^propose-answer-2/(?P<question_id>\d+)/$', views.CreateAnswer2View.as_view(), name='propose_answer2'),
    url(r'^propose-answer-3/(?P<question_id>\d+)/$', views.CreateAnswer3View.as_view(), name='propose_answer3'),
    url(r'^propose-answer-4/(?P<question_id>\d+)/$', views.CreateAnswer4View.as_view(), name='propose_answer4'),
    url(r'^propose-answer-5/(?P<question_id>\d+)/$', views.CreateAnswer5View.as_view(), name='propose_answer5'),
    url(r'^propose-answer-6/(?P<question_id>\d+)/$', views.CreateAnswer6View.as_view(), name='propose_answer6'),
    url(r'^propose-answer-7/(?P<question_id>\d+)/$', views.CreateAnswer7View.as_view(), name='propose_answer7'),
    url(r'^propose-answer-8/(?P<question_id>\d+)/$', views.CreateAnswer8View.as_view(), name='propose_answer8'),
    url(r'^question/vote/$', views.question_vote, name='question_vote'),
    url(r'^question/vote-2/$', views.question_vote2, name='question_vote2'),
    url(r'^question/vote-3/$', views.question_vote3, name='question_vote3'),
    url(r'^question/vote-4/$', views.question_vote4, name='question_vote4'),
    url(r'^question/vote-5/$', views.question_vote5, name='question_vote5'),
    url(r'^question/vote-6/$', views.question_vote6, name='question_vote6'),
    url(r'^question/vote-7/$', views.question_vote7, name='question_vote7'),
    url(r'^question/vote-8/$', views.question_vote8, name='question_vote8'),
    url(r'^answer/vote/$', views.answer_vote, name='answer_vote'),
    url(r'^answer/vote-2/$', views.answer_vote2, name='answer_vote2'),
    url(r'^answer/vote-3/$', views.answer_vote3, name='answer_vote3'),
    url(r'^answer/vote-4/$', views.answer_vote4, name='answer_vote4'),
    url(r'^answer/vote-5/$', views.answer_vote5, name='answer_vote5'),
    url(r'^answer/vote-6/$', views.answer_vote6, name='answer_vote6'),
    url(r'^answer/vote-7/$', views.answer_vote7, name='answer_vote7'),
    url(r'^answer/vote-8/$', views.answer_vote8, name='answer_vote8'),
    url(r'^accept-answer/$', views.accept_answer, name='accept_answer'),
    url(r'^accept-answer-2/$', views.accept_answer2, name='accept_answer2'),
    url(r'^accept-answer-3/$', views.accept_answer3, name='accept_answer3'),
    url(r'^accept-answer-4/$', views.accept_answer4, name='accept_answer4'),
    url(r'^accept-answer-5/$', views.accept_answer5, name='accept_answer5'),
    url(r'^accept-answer-6/$', views.accept_answer6, name='accept_answer6'),
    url(r'^accept-answer-7/$', views.accept_answer7, name='accept_answer7'),
    url(r'^accept-answer-8/$', views.accept_answer8, name='accept_answer8'),
]

bootcamp/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from graphene_django.views import GraphQLView

urlpatterns = [
    url(r'^$',
        TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'), name='about'),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    # User management
    url(r'^users/', include('bootcamp.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),
    # Third party apps here
    url(r'^comments/', include('django_comments.urls')),
    url(r'^graphql', GraphQLView.as_view(graphiql=True)),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^invitations/', include('invitations.urls', namespace='invitations')),
    # Local apps here
    url(r'^notifications/',
        include('bootcamp.notifications.urls', namespace='notifications')),
    url(r'^articles/',
        include('bootcamp.articles.urls', namespace='articles')),
    url(r'^news/', include('bootcamp.news.urls', namespace='news')),
    url(r'^messages/',
        include('bootcamp.messager.urls', namespace='messager')),
    url(r'^qa/', include('bootcamp.qa.urls', namespace='qa')),
    url(r'^search/', include('bootcamp.search.urls', namespace='search')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

bootcamp/articles/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from hitcount.views import HitCountDetailView

from bootcamp.helpers import AuthorRequiredMixin
from bootcamp.articles.models import Article
from bootcamp.articles.forms import ArticleForm


class ArticlesListView(LoginRequiredMixin, ListView):
    """Basic ListView implementation to call the published articles list."""
    model = Article
    paginate_by = 15
    context_object_name = "articles"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['popular_tags'] = Article.objects.get_counted_tags()
        return context

    def get_queryset(self, **kwargs):
        return Article.objects.get_published()


class DraftsListView(ArticlesListView):
    """Overriding the original implementation to call the drafts articles
    list."""
    def get_queryset(self, **kwargs):
        return Article.objects.get_drafts()


class CreateArticleView(LoginRequiredMixin, CreateView):
    """Basic CreateView implementation to create new articles."""
    model = Article
    message = _("Ваш артикль был создан.")
    form_class = ArticleForm
    template_name = 'articles/article_create.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse('articles:list')


class EditArticleView(LoginRequiredMixin, AuthorRequiredMixin, UpdateView):
    """Basic EditView implementation to edit existing articles."""
    model = Article
    message = _("Ваш артикль был изменен.")
    form_class = ArticleForm
    template_name = 'articles/article_update.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse('articles:list')


class DetailArticleView(LoginRequiredMixin, HitCountDetailView):
    """Basic DetailView implementation to call an individual article."""
    model = Article
    count_hit = True

bootcamp/messager/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import render
from django.views.generic import ListView

from bootcamp.messager.models import Message
from bootcamp.helpers import ajax_required


class MessagesListView(LoginRequiredMixin, ListView):
    """CBV to render the inbox, showing by default the most recent
    conversation as the active one.
    """
    model = Message
    paginate_by = 50
    template_name = "messager/message_list.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['users_list'] = get_user_model().objects.filter(
            is_active=True).exclude(
                username=self.request.user).order_by('username')
        last_conversation = Message.objects.get_most_recent_conversation(
            self.request.user
        )
        context['active'] = last_conversation.username
        return context

    def get_queryset(self):
        active_user = Message.objects.get_most_recent_conversation(
            self.request.user)
        return Message.objects.get_conversation(active_user, self.request.user)


class ConversationListView(MessagesListView):
    """CBV to render the inbox, showing an specific conversation with a given
    user, who requires to be active too."""
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['active'] = self.kwargs["username"]
        return context

    def get_queryset(self):
        active_user = get_user_model().objects.get(
            username=self.kwargs["username"])
        return Message.objects.get_conversation(active_user, self.request.user)


@login_required
@ajax_required
def send_message(request):
    """AJAX Functional view to recieve just the minimum information, process
    and create the new message and return the new data to be attached to the
    conversation stream."""
    if request.method == 'POST':
        sender = request.user
        recipient_username = request.POST.get('to')
        recipient = get_user_model().objects.get(username=recipient_username)
        message = request.POST.get('message')
        if len(message.strip()) == 0:
            return HttpResponse()

        if sender != recipient:
            msg = Message.send_message(sender, recipient, message)
            return render(request, 'messager/single_message.html',
                          {'message': msg})

        return HttpResponse()

    else:
        return HttpResponseBadRequest()


@login_required
@ajax_required
def receive_message(request):
    """Simple AJAX functional view to return a rendered single message on the
    receiver side providing realtime connections."""
    if request.method == 'GET':
        message_id = request.GET.get('message_id')
        message = Message.objects.get(pk=message_id)
        return render(request,
                      'messager/single_message.html', {'message': message})

    else:
        return HttpResponseBadRequest()

bootcamp/notifications/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import ugettext_lazy as _
from django.views.generic import ListView

from bootcamp.notifications.models import Notification


class NotificationUnreadListView(LoginRequiredMixin, ListView):
    """Basic ListView implementation to show the unread notifications for
    the actual user"""
    model = Notification
    context_object_name = 'notification_list'
    template_name = 'notifications/notification_list.html'

    def get_queryset(self, **kwargs):
        return self.request.user.notifications.unread()


@login_required
def mark_all_as_read(request):
    """View to call the model method which marks as read all the notifications
    directed to the actual user."""
    request.user.notifications.mark_all_as_read()
    _next = request.GET.get('next')
    messages.add_message(
        request, messages.SUCCESS,
        _(f'All notifications to {request.user.username} have been marked as read.'))

    if _next:
        return redirect(_next)

    return redirect('notifications:unread')


@login_required
def mark_as_read(request, slug=None):
    """View to call the model method which mark as read the provided
    notification."""
    if slug:
        notification = get_object_or_404(Notification, slug=slug)
        notification.mark_as_read()

    messages.add_message(
        request, messages.SUCCESS,
        _(f'The notification {notification.slug} has been marked as read.'))
    _next = request.GET.get('next')

    if _next:
        return redirect(_next)

    return redirect('notifications:unread')


@login_required
def get_latest_notifications(request):
    notifications = request.user.notifications.get_most_recent()
    return render(request,
                  'notifications/most_recent.html',
                  {'notifications': notifications})

bootcamp/templates/qa/question_list.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{% trans "Вопросы" %}{% endblock %}

{% block head %}
  <link href="{% static 'css/qa.css' %}" rel="stylesheet">
{% endblock head %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
     <!--  <li class="breadcrumb-item"><a href="{% url 'news:list' %}">{% trans 'Лента' %}</a></li> -->
      <li class="breadcrumb-item" aria-current="page" style="font-size: 1.5rem">{% trans 'Вопросы' %}</li>
<div class="ml-auto">
<a href="{% url 'qa:ask_question' %}" class="btn btn-primary pull-right" style="background-color: #004a7a">
      <i class="fa fa-plus-circle" aria-hidden="true" ></i> {% trans "Создать тему" %}
    </a>
</div>
    </ol>
  </nav>
<!--   <div class="page-header">

    <h1>{% trans "Вопросы" %}</h1>
  </div> -->
  <div class="card my-4">
    <h5 class="card-header">{% trans 'Вопросы по теме' %}</h5>
    <div class="card-body">
      {% for tag, count in popular_tags %}
        <a href="#"><span class="badge badge-info" style="background-color: #004a7a">{{ count }} {{ tag }}</span></a>
      {% endfor %}
    </div>
  </div>
  <div>
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link{% if active == 'unanswered' %} active{% endif %}" href="{% url 'qa:index_noans' %}" >
          {% trans "Неотвеченные" %}
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link{% if active == 'answered' %} active{% endif %}" href="{% url 'qa:index_ans' %}" style="color: #004a7a">
          {% trans "Отвеченные" %}
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link{% if active == 'all' %} active{% endif %}" href="{% url 'qa:index_all' %}" style="color: #004a7a">
          {% trans "Все вопросы" %}
        </a>
      </li>
    </ul>
    {% for question in questions %}
      {% include 'qa/question_sample.html' with question=question %}
    {% empty %}
      <h4 class="no-data">{% trans "Нет вопросов для показа" %}</h4>
    {% endfor %}

    {% if is_paginated %}
      <ul class="pagination justify-content-center mb-4">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&larr; {% trans 'Никогда' %}</a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#"><span>&larr;</span></a></li>
        {% endif %}
        {% for i in paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="page-item disabled"><a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{% trans 'Старые вопросы' %} &rarr;</a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#"><span>&rarr;</span></a></li>
        {% endif %}
      </ul>
    {% endif %}
  </div>
{% endblock content %}

<style type="text/css">

</style>
{% block modal %}
  <script src="{% static 'js/qa.js' %}"></script>
{% endblock modal %}

bootcamp/templates/qa/question_list_4.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{% trans "Вопросы" %}{% endblock %}

{% block head %}
  <link href="{% static 'css/qa.css' %}" rel="stylesheet">
{% endblock head %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
     <!--  <li class="breadcrumb-item"><a href="{% url 'news:list' %}">{% trans 'Лента' %}</a></li> -->
        <li class="breadcrumb-item" aria-current="page" style="font-size: 1.5rem">{% trans 'Вопросы' %}</li>
<div class="ml-auto">
<a href="{% url 'qa:ask_question4' %}" class="btn btn-primary pull-right" style="background-color: #004a7a">
      <i class="fa fa-plus-circle" aria-hidden="true" ></i> {% trans "Создать тему" %}
    </a>
</div>
    </ol>
  </nav>
<!--   <div class="page-header">

    <h1>{% trans "Вопросы" %}</h1>
  </div> -->
  <div class="card my-4">
    <h5 class="card-header">{% trans 'Вопросы по теме' %}</h5>
    <div class="card-body">
      {% for tag, count in popular_tags %}
        <a href="#"><span class="badge badge-info" style="background-color: #004a7a">{{ count }} {{ tag }}</span></a>
      {% endfor %}
    </div>
  </div>
  <div>
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link{% if active == 'unanswered' %} active{% endif %}" href="{% url 'qa:index_noans4' %}" >
          {% trans "Неотвеченные" %}
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link{% if active == 'answered' %} active{% endif %}" href="{% url 'qa:index_ans4' %}" style="color: #004a7a">
          {% trans "Отвеченные" %}
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link{% if active == 'all' %} active{% endif %}" href="{% url 'qa:index_all4' %}" style="color: #004a7a">
          {% trans "Все вопросы" %}
        </a>
      </li>
    </ul>
    {% for question in questions %}
      {% include 'qa/question_sample_4.html' with question=question %}
    {% empty %}
      <h4 class="no-data">{% trans "Нет вопросов для показа" %}</h4>
    {% endfor %}

    {% if is_paginated %}
      <ul class="pagination justify-content-center mb-4">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&larr; {% trans 'Никогда' %}</a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#"><span>&larr;</span></a></li>
        {% endif %}
        {% for i in paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="page-item disabled"><a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{% trans 'Старые вопросы' %} &rarr;</a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#"><span>&rarr;</span></a></li>
        {% endif %}
      </ul>
    {% endif %}
  </div>
{% endblock content %}

<style type="text/css">

</style>
{% block modal %}
  <script src="{% static 'js/qa.js' %}"></script>
{% endblock modal %}

bootcamp/templates/qa/question_list_5.html
{% extends 'base.html' %}
{% load static i18n %}

{% block title %}{% trans "Вопросы" %}{% endblock %}

{% block head %}
  <link href="{% static 'css/qa.css' %}" rel="stylesheet">
{% endblock head %}

{% block content %}
  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
     <!--  <li class="breadcrumb-item"><a href="{% url 'news:list' %}">{% trans 'Лента' %}</a></li> -->
        <li class="breadcrumb-item" aria-current="page" style="font-size: 1.5rem">{% trans 'Вопросы' %}</li>
<div class="ml-auto">
<a href="{% url 'qa:ask_question5' %}" class="btn btn-primary pull-right" style="background-color: #004a7a">
      <i class="fa fa-plus-circle" aria-hidden="true" ></i> {% trans "Создать тему" %}
    </a>
</div>
    </ol>
  </nav>
<!--   <div class="page-header">

    <h1>{% trans "Вопросы" %}</h1>
  </div> -->
  <div class="card my-4">
    <h5 class="card-header">{% trans 'Вопросы по теме' %}</h5>
    <div class="card-body">
      {% for tag, count in popular_tags %}
        <a href="#"><span class="badge badge-info" style="background-color: #004a7a">{{ count }} {{ tag }}</span></a>
      {% endfor %}
    </div>
  </div>
  <div>
    <ul class="nav nav-tabs">
      <li class="nav-item">
        <a class="nav-link{% if active == 'unanswered' %} active{% endif %}" href="{% url 'qa:index_noans5' %}" >
          {% trans "Неотвеченные" %}
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link{% if active == 'answered' %} active{% endif %}" href="{% url 'qa:index_ans5' %}" style="color: #004a7a">
          {% trans "Отвеченные" %}
        </a>
      </li>
      <li class="nav-item">
        <a class="nav-link{% if active == 'all' %} active{% endif %}" href="{% url 'qa:index_all5' %}" style="color: #004a7a">
          {% trans "Все вопросы" %}
        </a>
      </li>
    </ul>
    {% for question in questions %}
      {% include 'qa/question_sample_5.html' with question=question %}
    {% empty %}
      <h4 class="no-data">{% trans "Нет вопросов для показа" %}</h4>
    {% endfor %}

    {% if is_paginated %}
      <ul class="pagination justify-content-center mb-4">
        {% if page_obj.has_previous %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.previous_page_number }}">&larr; {% trans 'Никогда' %}</a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#"><span>&larr;</span></a></li>
        {% endif %}
        {% for i in paginator.page_range %}
          {% if page_obj.number == i %}
            <li class="page-item disabled"><a class="page-link" href="#">{{ i }} <span class="sr-only">(current)</span></a></li>
          {% else %}
            <li class="page-item"><a class="page-link" href="?page={{ i }}">{{ i }}</a></li>
          {% endif %}
        {% endfor %}
        {% if page_obj.has_next %}
          <li class="page-item"><a class="page-link" href="?page={{ page_obj.next_page_number }}">{% trans 'Старые вопросы' %} &rarr;</a></li>
        {% else %}
          <li class="page-item disabled"><a class="page-link" href="#"><span>&rarr;</span></a></li>
        {% endif %}
      </ul>
    {% endif %}
  </div>
{% endblock content %}

<style type="text/css">

</style>
{% block modal %}
  <script src="{% static 'js/qa.js' %}"></script>
{% endblock modal %}