bootcamp/news/urls.py
from django.conf.urls import url

from bootcamp.news import views

app_name = 'news'
urlpatterns = [
    url(r'^$', views.NewsListView.as_view(), name='list'),
    url(r'^delete/(?P<pk>[-\w]+)/$',
        views.NewsDeleteView.as_view(), name='delete_news'),
    url(r'^post-news/$', views.post_news, name='post_news'),
    url(r'^like/$', views.like, name='like_post'),
    url(r'^dislike/$', views.dislike, name='dislike_post'),
    url(r'^get-thread/$', views.get_thread, name='get_thread'),
    url(r'^post-comment/$', views.post_comment, name='post_comments'),
    url(r'^update-interactions/$', views.update_interactions, name='update_interactions'),
    url(r'^news-table/$', views.tablify, name='tablify'),
]

bootcamp/qa/urls.py
from django.conf.urls import url

from bootcamp.qa import views

app_name = 'qa'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='question_main'),
    url(r'^main/$', views.FakeIndexView.as_view(), name='question_fake_main'),
    url(r'^question-list/$', views.QuestionListView.as_view(), name='index_noans'),
    url(r'^question-list-2/$', views.Question2ListView.as_view(), name='index_noans2'),
    url(r'^question-list-3/$', views.Question3ListView.as_view(), name='index_noans3'),
    url(r'^question-list-4/$', views.Question4ListView.as_view(), name='index_noans4'),
    url(r'^question-list-5/$', views.Question5ListView.as_view(), name='index_noans5'),
    url(r'^question-list-6/$', views.Question6ListView.as_view(), name='index_noans6'),
    url(r'^question-list-7/$', views.Question7ListView.as_view(), name='index_noans7'),
    url(r'^question-list-8/$', views.Question8ListView.as_view(), name='index_noans8'),
    url(r'^answered/$', views.QuestionAnsListView.as_view(), name='index_ans'),
    url(r'^answered-2/$', views.Question2AnsListView.as_view(), name='index_ans2'),
    url(r'^answered-3/$', views.Question3AnsListView.as_view(), name='index_ans3'),
    url(r'^answered-4/$', views.Question4AnsListView.as_view(), name='index_ans4'),
    url(r'^answered-5/$', views.Question5AnsListView.as_view(), name='index_ans5'),
    url(r'^answered-6/$', views.Question6AnsListView.as_view(), name='index_ans6'),
    url(r'^answered-7/$', views.Question7AnsListView.as_view(), name='index_ans7'),
    url(r'^answered-8/$', views.Question8AnsListView.as_view(), name='index_ans8'),
    url(r'^indexed/$', views.QuestionsIndexListView.as_view(), name='index_all'),
    url(r'^indexed-2/$', views.Questions2IndexListView.as_view(), name='index_all2'),
    url(r'^indexed-3/$', views.Questions3IndexListView.as_view(), name='index_all3'),
    url(r'^indexed-4/$', views.Questions4IndexListView.as_view(), name='index_all4'),
    url(r'^indexed-5/$', views.Questions5IndexListView.as_view(), name='index_all5'),
    url(r'^indexed-6/$', views.Questions6IndexListView.as_view(), name='index_all6'),
    url(r'^indexed-7/$', views.Questions7IndexListView.as_view(), name='index_all7'),
    url(r'^indexed-8/$', views.Questions8IndexListView.as_view(), name='index_all8'),
    url(r'^question-detail/(?P<pk>\d+)/$', views.QuestionDetailView.as_view(), name='question_detail'),
    url(r'^question-detail-2/(?P<pk>\d+)/$', views.Question2DetailView.as_view(), name='question_detail2'),
    url(r'^question-detail-3/(?P<pk>\d+)/$', views.Question3DetailView.as_view(), name='question_detail3'),
    url(r'^question-detail-4/(?P<pk>\d+)/$', views.Question4DetailView.as_view(), name='question_detail4'),
    url(r'^question-detail-5/(?P<pk>\d+)/$', views.Question5DetailView.as_view(), name='question_detail5'),
    url(r'^question-detail-6/(?P<pk>\d+)/$', views.Question6DetailView.as_view(), name='question_detail6'),
    url(r'^question-detail-7/(?P<pk>\d+)/$', views.Question7DetailView.as_view(), name='question_detail7'),
    url(r'^question-detail-8/(?P<pk>\d+)/$', views.Question8DetailView.as_view(), name='question_detail8'),
    url(r'^ask-question/$', views.CreateQuestionView.as_view(), name='ask_question'),
    url(r'^ask-question-2/$', views.CreateQuestion2View.as_view(), name='ask_question2'),
    url(r'^ask-question-3/$', views.CreateQuestion3View.as_view(), name='ask_question3'),
    url(r'^ask-question-4/$', views.CreateQuestion4View.as_view(), name='ask_question4'),
    url(r'^ask-question-5/$', views.CreateQuestion5View.as_view(), name='ask_question5'),
    url(r'^ask-question-6/$', views.CreateQuestion6View.as_view(), name='ask_question6'),
    url(r'^ask-question-7/$', views.CreateQuestion7View.as_view(), name='ask_question7'),
    url(r'^ask-question-8/$', views.CreateQuestion8View.as_view(), name='ask_question8'),
    url(r'^propose-answer/(?P<question_id>\d+)/$', views.CreateAnswerView.as_view(), name='propose_answer'),
    url(r'^propose-answer-2/(?P<question_id>\d+)/$', views.CreateAnswer2View.as_view(), name='propose_answer2'),
    url(r'^propose-answer-3/(?P<question_id>\d+)/$', views.CreateAnswer3View.as_view(), name='propose_answer3'),
    url(r'^propose-answer-4/(?P<question_id>\d+)/$', views.CreateAnswer4View.as_view(), name='propose_answer4'),
    url(r'^propose-answer-5/(?P<question_id>\d+)/$', views.CreateAnswer5View.as_view(), name='propose_answer5'),
    url(r'^propose-answer-6/(?P<question_id>\d+)/$', views.CreateAnswer6View.as_view(), name='propose_answer6'),
    url(r'^propose-answer-7/(?P<question_id>\d+)/$', views.CreateAnswer7View.as_view(), name='propose_answer7'),
    url(r'^propose-answer-8/(?P<question_id>\d+)/$', views.CreateAnswer8View.as_view(), name='propose_answer8'),
    url(r'^question/vote/$', views.question_vote, name='question_vote'),
    url(r'^question/vote-2/$', views.question_vote2, name='question_vote2'),
    url(r'^question/vote-3/$', views.question_vote3, name='question_vote3'),
    url(r'^question/vote-4/$', views.question_vote4, name='question_vote4'),
    url(r'^question/vote-5/$', views.question_vote5, name='question_vote5'),
    url(r'^question/vote-6/$', views.question_vote6, name='question_vote6'),
    url(r'^question/vote-7/$', views.question_vote7, name='question_vote7'),
    url(r'^question/vote-8/$', views.question_vote8, name='question_vote8'),
    url(r'^answer/vote/$', views.answer_vote, name='answer_vote'),
    url(r'^answer/vote-2/$', views.answer_vote2, name='answer_vote2'),
    url(r'^answer/vote-3/$', views.answer_vote3, name='answer_vote3'),
    url(r'^answer/vote-4/$', views.answer_vote4, name='answer_vote4'),
    url(r'^answer/vote-5/$', views.answer_vote5, name='answer_vote5'),
    url(r'^answer/vote-6/$', views.answer_vote6, name='answer_vote6'),
    url(r'^answer/vote-7/$', views.answer_vote7, name='answer_vote7'),
    url(r'^answer/vote-8/$', views.answer_vote8, name='answer_vote8'),
    url(r'^accept-answer/$', views.accept_answer, name='accept_answer'),
    url(r'^accept-answer-2/$', views.accept_answer2, name='accept_answer2'),
    url(r'^accept-answer-3/$', views.accept_answer3, name='accept_answer3'),
    url(r'^accept-answer-4/$', views.accept_answer4, name='accept_answer4'),
    url(r'^accept-answer-5/$', views.accept_answer5, name='accept_answer5'),
    url(r'^accept-answer-6/$', views.accept_answer6, name='accept_answer6'),
    url(r'^accept-answer-7/$', views.accept_answer7, name='accept_answer7'),
    url(r'^accept-answer-8/$', views.accept_answer8, name='accept_answer8'),
]

bootcamp/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from graphene_django.views import GraphQLView

urlpatterns = [
    url(r'^$',
        TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'), name='about'),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    # User management
    url(r'^users/', include('bootcamp.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),
    # Third party apps here
    url(r'^comments/', include('django_comments.urls')),
    url(r'^graphql', GraphQLView.as_view(graphiql=True)),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^invitations/', include('invitations.urls', namespace='invitations')),
    # Local apps here
    url(r'^notifications/',
        include('bootcamp.notifications.urls', namespace='notifications')),
    url(r'^articles/',
        include('bootcamp.articles.urls', namespace='articles')),
    url(r'^news/', include('bootcamp.news.urls', namespace='news')),
    url(r'^messages/',
        include('bootcamp.messager.urls', namespace='messager')),
    url(r'^qa/', include('bootcamp.qa.urls', namespace='qa')),
    url(r'^search/', include('bootcamp.search.urls', namespace='search')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

bootcamp/articles/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from hitcount.views import HitCountDetailView

from bootcamp.helpers import AuthorRequiredMixin
from bootcamp.articles.models import Article
from bootcamp.articles.forms import ArticleForm


class ArticlesListView(LoginRequiredMixin, ListView):
    """Basic ListView implementation to call the published articles list."""
    model = Article
    paginate_by = 15
    context_object_name = "articles"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['popular_tags'] = Article.objects.get_counted_tags()
        return context

    def get_queryset(self, **kwargs):
        return Article.objects.get_published()


class DraftsListView(ArticlesListView):
    """Overriding the original implementation to call the drafts articles
    list."""
    def get_queryset(self, **kwargs):
        return Article.objects.get_drafts()


class CreateArticleView(LoginRequiredMixin, CreateView):
    """Basic CreateView implementation to create new articles."""
    model = Article
    message = _("Ваш артикль был создан.")
    form_class = ArticleForm
    template_name = 'articles/article_create.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse('articles:list')


class EditArticleView(LoginRequiredMixin, AuthorRequiredMixin, UpdateView):
    """Basic EditView implementation to edit existing articles."""
    model = Article
    message = _("Ваш артикль был изменен.")
    form_class = ArticleForm
    template_name = 'articles/article_update.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse('articles:list')


class DetailArticleView(LoginRequiredMixin, HitCountDetailView):
    """Basic DetailView implementation to call an individual article."""
    model = Article
    count_hit = True

bootcamp/messager/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import render
from django.views.generic import ListView

from bootcamp.messager.models import Message
from bootcamp.helpers import ajax_required


class MessagesListView(LoginRequiredMixin, ListView):
    """CBV to render the inbox, showing by default the most recent
    conversation as the active one.
    """
    model = Message
    paginate_by = 50
    template_name = "messager/message_list.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['users_list'] = get_user_model().objects.filter(
            is_active=True).exclude(
                username=self.request.user).order_by('username')
        last_conversation = Message.objects.get_most_recent_conversation(
            self.request.user
        )
        context['active'] = last_conversation.username
        return context

    def get_queryset(self):
        active_user = Message.objects.get_most_recent_conversation(
            self.request.user)
        return Message.objects.get_conversation(active_user, self.request.user)


class ConversationListView(MessagesListView):
    """CBV to render the inbox, showing an specific conversation with a given
    user, who requires to be active too."""
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['active'] = self.kwargs["username"]
        return context

    def get_queryset(self):
        active_user = get_user_model().objects.get(
            username=self.kwargs["username"])
        return Message.objects.get_conversation(active_user, self.request.user)


@login_required
@ajax_required
def send_message(request):
    """AJAX Functional view to recieve just the minimum information, process
    and create the new message and return the new data to be attached to the
    conversation stream."""
    if request.method == 'POST':
        sender = request.user
        recipient_username = request.POST.get('to')
        recipient = get_user_model().objects.get(username=recipient_username)
        message = request.POST.get('message')
        if len(message.strip()) == 0:
            return HttpResponse()

        if sender != recipient:
            msg = Message.send_message(sender, recipient, message)
            return render(request, 'messager/single_message.html',
                          {'message': msg})

        return HttpResponse()

    else:
        return HttpResponseBadRequest()


@login_required
@ajax_required
def receive_message(request):
    """Simple AJAX functional view to return a rendered single message on the
    receiver side providing realtime connections."""
    if request.method == 'GET':
        message_id = request.GET.get('message_id')
        message = Message.objects.get(pk=message_id)
        return render(request,
                      'messager/single_message.html', {'message': message})

    else:
        return HttpResponseBadRequest()

bootcamp/notifications/views.py
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import get_object_or_404, redirect, render
from django.utils.translation import ugettext_lazy as _
from django.views.generic import ListView

from bootcamp.notifications.models import Notification


class NotificationUnreadListView(LoginRequiredMixin, ListView):
    """Basic ListView implementation to show the unread notifications for
    the actual user"""
    model = Notification
    context_object_name = 'notification_list'
    template_name = 'notifications/notification_list.html'

    def get_queryset(self, **kwargs):
        return self.request.user.notifications.unread()


@login_required
def mark_all_as_read(request):
    """View to call the model method which marks as read all the notifications
    directed to the actual user."""
    request.user.notifications.mark_all_as_read()
    _next = request.GET.get('next')
    messages.add_message(
        request, messages.SUCCESS,
        _(f'All notifications to {request.user.username} have been marked as read.'))

    if _next:
        return redirect(_next)

    return redirect('notifications:unread')


@login_required
def mark_as_read(request, slug=None):
    """View to call the model method which mark as read the provided
    notification."""
    if slug:
        notification = get_object_or_404(Notification, slug=slug)
        notification.mark_as_read()

    messages.add_message(
        request, messages.SUCCESS,
        _(f'The notification {notification.slug} has been marked as read.'))
    _next = request.GET.get('next')

    if _next:
        return redirect(_next)

    return redirect('notifications:unread')


@login_required
def get_latest_notifications(request):
    notifications = request.user.notifications.get_most_recent()
    return render(request,
                  'notifications/most_recent.html',
                  {'notifications': notifications})

bootcamp/templates/news/news_list.html
{% extends 'base.html' %}
{% load static i18n humanize %}
{% load thumbnail %}


{% block head %}
  <link href="{% static 'css/news.css' %}?v=1" rel="stylesheet">
{% endblock head %}


{% block content %}
    <!-- Container -->
    <div class="container" style="margin-top:15px">
      <div class="row">
        <div class="col-md-0">
        </div>
        <div class="col-md-12">
          <div class="container">
            <div class="row">
              <div class="col">
{#                <a href="{% url 'news:tablify' %}"><h3>{% trans 'Законопроекты' %}</h3></a>#}
                  <h3 style="color:#004a7a">Список законопроектов от <font style="color:#ffb100">Атамекен</font></h3>
              </div>

                {%  if user.is_superuser %}
              <div class="col col-md-3" style="margin-right:35px">
                <button type="button" class="button3 btn btn-primary" data-toggle="modal" data-target="#newsFormModal" style="background-color:  #004a7a;">
                  <i class="fa fa-share-alt" aria-hidden="true"></i> {% trans 'Опубликовать' %}
                </button>
              </div>
                {% endif %}
            </div>
          </div>

          <!-- Modals -->
          {% include 'news/news_form_modal.html' %}
          {% include 'news/news_thread_modal.html' %}
          <!-- End Modals -->

          <!-- News List -->
          <div class="stream-update">
            <a href="{% url 'news:list' %}"><span class="new-posts"></span> {% trans 'Тут новые посты' %}</a>
          </div>
          <div class="infinite-container">
            <ul class="stream">
              {% for news in news_list %}
                {% include 'news/news_single.html' with news=news %}
              {% endfor %}
            </ul>
          </div>
          <div class="load">
            {% if page_obj.has_next %}
              <a class="infinite-more-link" href="?page={{ page_obj.next_page_number }}"><img src="{% static 'img/loading.gif' %}"></a>
            {% endif %}
          </div>
          <!-- End News List -->
        </div>
      </div>
    </div>
    <!-- End container -->

{% endblock content %}

{% block modal %}
    <style>
        a {
            color:#004a7a;
        }
    </style>
  <script src="{% static 'js/jquery.waypoints.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/infinite.min.js' %}" type="text/javascript"></script>
  <script src="{% static 'js/news.js' %}" type="text/javascript"></script>
  <script>
    var infinite = new Waypoint.Infinite({
      element: $('.infinite-container')[0],
      onBeforePageLoad: function () {
        $('.load').show();
      },
      onAfterPageLoad: function ($items) {
        $('.load').hide();
      }
    });
  </script>
{% endblock modal %}

bootcamp/templates/news/news_single.html
{% load i18n %}
{% load humanize static %}
{% load thumbnail %}
<li class="infinite-item card container" news-id="{{ news.uuid_id }}">
  <div class="card-body">
{#    <div class="profile-picture">#}
{#      {% thumbnail news.user.picture "x60" as im %}#}
{#        <img src="{{ im.url }}" class="pull-left" style="border-radius: 50%;" alt="{% trans 'Фото пользователя' %}" class="user-image">#}
{#      {% empty %}#}
{#        <img src="{% static 'img/user.png' %}" class="pull-left" height="60px" alt="{% trans 'Нет фото профиля' %}" />#}
{#      {% endthumbnail %}#}
{#    </div>#}
    <div class="post">
      {% if news.user == request.user %}

          <a href="{% url 'news:delete_news' news.pk %}" class="deletePost" style="padding:5px">
{#          <i class="fa fa-times pull-right" </i>#}
          <i class="fa fa-trash-o pull-right" aria-hidden="true" title="{% trans 'Нажмите чтобы удалить новость' %}"></i>
        </a>
{#           <a href="{% url 'news:delete_news' news.pk %}" class="deletePost" style="padding:2rem">#}
{#           <i class="fa fa-pencil-square-o pull-right" aria-hidden="true"></i>#}
{#          </a>#}
      {% endif %}
{#      <p>#}
{#        <strong>#}
{#          <a href="{% url 'users:detail' news.user.username  %}">{{ news.user.get_profile_name|title }}</a>#}
{#        </strong>#}
{#      </p>#}
    <table class="table  table-bordered table-hover">
        <thead>
    <tr>
         <th scope="col" class="first">Наименование</th>
         <th scope="col" class="second">Редакция проекта</th>
         <th scope="col" class="second">Предлагаемая редакция</th>
         <th scope="col" class="second">Обоснование</th>
    </tr>
        </thead>

        <tbody>
    <tr>
      <td>{{ news.content }}</td>
      <td>{{ news.content_two }}</td>
      <td>{{ news.content_three }}</td>
      <td>{{ news.content_four }}</td>
    </tr>
        </tbody>
    </table>

      {% if news.image %}
        <img class="card-img-top" src="{{ news.image }}" alt="Фото карточки">
      {% endif %}
    </div>
  </div>
    <form id="interactions" role="form" method="post" action="#!" onsubmit="return false">
        {% csrf_token %}
        <div class="interaction" id="interaction" style="margin-left:2rem">
            <a href="#!" class="like" title="{% for i in news.get_likers %}{{ i }}&#10;{% endfor %}">
                {% if request.user in news.get_likers %}
                    <i class="fa fa-chevron-up vote up-voted question-voted" aria-hidden="true"></i>
                {% else %}
                    <i class="fa fa-chevron-up vote up-vote question-vote" aria-hidden="true"></i>
                {% endif %}
                <span class="like-count">{{ news.count_likers }}</span>
            </a>

            <a href="#!" class="dislike" title="{% for i in news.get_dislikers %}{{ i }}&#10;{% endfor %}">
                {% if request.user in news.get_dislikers %}
                    <i class="fa fa-chevron-down voted down-vote question-voted" aria-hidden="true"></i>
                {% else %}
                    <i class="fa fa-chevron-down vote down-vote question-vote" aria-hidden="true"></i>
                {% endif %}
                <span class="dislike-count">{{ news.count_dislikers }}</span>
            </a>

            <a href="#!" class="comment"><i class="fa fa-comment-o" aria-hidden="true"></i>
                <span class="comment-count">{{ news.count_thread }}</span>
            </a>
                <span class="timestamp" style="padding-right:2rem">{{ news.timestamp|date:'G:i | d.m.Y ' }}</span>
        </div>
    </form>
</li>
<style>
  .deletePost i:hover {
    color: red;
  }
  th {
    background-color: #F5F5F5;
    color: #004a7a;
    width:25%;
  }
    {#.first {#}
    {#    width:16%;#}
    {#}#}
    {#.second {#}
    {#    width:21%;#}
    {#}#}
    @media
    only screen
    and (max-width: 760px), (min-device-width: 768px)
    and (max-device-width: 1024px)  {

    /* Force table to not be like tables anymore */
    table, thead, tbody, th, td, tr {
      display: block;
    }

    /* Hide table headers (but not display: none;, for accessibility) */
    thead tr {
      position: absolute;
      top: -9999px;
      left: -9999px;
    }

    tr {
      margin: 0 0 1rem 0;

    }

    td {
      /* Behave  like a "row" */
      border: none;
      border-bottom: 1px solid #eee;
      position: relative;
      padding-left: 50%;

    }

    td:before {

    }

    /*
    Label the data
    You could also use a data-* attribute and content for this. That way "bloats" the HTML, this way means you need to keep HTML and CSS in sync. Lea Verou has a clever way to handle with text-shadow.
    */
    td:nth-of-type(1):before {
      content: "Наименование: ";
      margin-left:6px;
      font-weight:bold;
    }
    td:nth-of-type(2):before {
      content: "Редакция проекта: ";
      margin-left:6px;
      font-weight:bold;
    }
    td:nth-of-type(3):before {
      content: "Предлагаемая редакция: ";
      margin-left:6px;
      font-weight:bold;
    }
    td:nth-of-type(4):before {
      content: "Обоснование: ";
      margin-left:6px;
      font-weight:bold;
    }
  }
</style>

bootcamp/templates/news/news_thread.html
{% load i18n %}
{% load humanize static %}
{% load thumbnail %}


{% for reply in thread %}
  <li class="card" news-id="{{ reply.uuid_id }}">
    <div class="card-body">
      <div class="profile-picture">
        {% thumbnail reply.user.picture "x60" as im %}
          <img src="{{ im.url }}" class="pull-left" style="border-radius: 50%;" alt="{% trans 'Фото пользователя' %}" class="user-image">
        {% empty %}
          <img src="{% static 'img/user.png' %}" class="pull-left" height="60px" alt="{% trans 'Нет фото профиля' %}" />
        {% endthumbnail %}
      </div>
      <div class="post">
        {% if reply.user == request.user %}
          <a href="{% url 'news:delete_news' reply.pk %}">
            <i class="fa fa-times pull-right" aria-hidden="true" title="{% trans 'Нажмите чтобы удалить новость' %}"></i>
          </a>
        {% endif %}
        <p>
          <strong>
            <a href="{% url 'users:detail' reply.user.username  %}">{{ reply.user.get_profile_name|title }}</a>
          </strong>
        </p>
        <p>{{ reply }}</p>
        {% if reply.image %}
          <img class="card-img-top" src="{{ reply.image }}" alt="Фото карточки">
        {% endif %}
      </div>
    </div>
    <form id="interactions" role="form" method="post" action="#!" onsubmit="return false">
        {% csrf_token %}
        <div class="interaction" id="interaction">
            <a href="#!" class="like" title="{% for i in news.get_likers %}{{ i }}&#10;{% endfor %}">
                {% if request.user in news.get_likers %}
                    <i class="fa fa-chevron-up vote up-voted question-voted" aria-hidden="true"></i>
                {% else %}
                    <i class="fa fa-chevron-up vote up-vote question-vote" aria-hidden="true"></i>
                {% endif %}
                <span class="like-count">{{ news.count_likers }}</span>
            </a>

            <a href="#!" class="dislike" title="{% for i in news.get_dislikers %}{{ i }}&#10;{% endfor %}">
                {% if request.user in news.get_dislikers %}
                    <i class="fa fa-chevron-down voted down-vote question-voted" aria-hidden="true"></i>
                {% else %}
                    <i class="fa fa-chevron-down vote down-vote question-vote" aria-hidden="true"></i>
                {% endif %}
                <span class="dislike-count">{{ news.count_dislikers }}</span>
            </a>

            <a href="#!" class="comment"><i class="fa fa-comment-o" aria-hidden="true"></i>
                <span class="comment-count">{{ news.count_thread }}</span>
            </a>
                <span class="timestamp">{{ news.timestamp|naturaltime }}</span>
        </div>
    </form>
  </li>
{% endfor %}