bootcamp/articles/urls.py
from django.conf.urls import url

from bootcamp.articles.views import (ArticlesListView, DraftsListView,
                                     CreateArticleView, EditArticleView,
                                     DetailArticleView)
app_name = 'articles'
urlpatterns = [
    url(r'^$', ArticlesListView.as_view(), name='list'),
    url(r'^write-new-article/$', CreateArticleView.as_view(), name='write_new'),
    url(r'^drafts/$', DraftsListView.as_view(), name='drafts'),
    url(r'^edit/(?P<pk>\d+)/$', EditArticleView.as_view(), name='edit_article'),
    url(r'^(?P<slug>[-\w]+)/$', DetailArticleView.as_view(), name='article'),
]

bootcamp/news/urls.py
from django.conf.urls import url

from bootcamp.news import views

app_name = 'news'
urlpatterns = [
    url(r'^$', views.NewsListView.as_view(), name='list'),
    url(r'^delete/(?P<pk>[-\w]+)/$',
        views.NewsDeleteView.as_view(), name='delete_news'),
    url(r'^post-news/$', views.post_news, name='post_news'),
    url(r'^like/$', views.like, name='like_post'),
    url(r'^dislike/$', views.dislike, name='dislike_post'),
    url(r'^get-thread/$', views.get_thread, name='get_thread'),
    url(r'^post-comment/$', views.post_comment, name='post_comments'),
    url(r'^update-interactions/$', views.update_interactions, name='update_interactions'),
    url(r'^news-table/$', views.tablify, name='tablify'),
]

bootcamp/qa/urls.py
from django.conf.urls import url

from bootcamp.qa import views

app_name = 'qa'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='question_main'),
    url(r'^main/$', views.FakeIndexView.as_view(), name='question_fake_main'),
    url(r'^question-list/$', views.QuestionListView.as_view(), name='index_noans'),
    url(r'^question-list-2/$', views.Question2ListView.as_view(), name='index_noans2'),
    url(r'^question-list-3/$', views.Question3ListView.as_view(), name='index_noans3'),
    url(r'^question-list-4/$', views.Question4ListView.as_view(), name='index_noans4'),
    url(r'^question-list-5/$', views.Question5ListView.as_view(), name='index_noans5'),
    url(r'^question-list-6/$', views.Question6ListView.as_view(), name='index_noans6'),
    url(r'^question-list-7/$', views.Question7ListView.as_view(), name='index_noans7'),
    url(r'^question-list-8/$', views.Question8ListView.as_view(), name='index_noans8'),
    url(r'^answered/$', views.QuestionAnsListView.as_view(), name='index_ans'),
    url(r'^answered-2/$', views.Question2AnsListView.as_view(), name='index_ans2'),
    url(r'^answered-3/$', views.Question3AnsListView.as_view(), name='index_ans3'),
    url(r'^answered-4/$', views.Question4AnsListView.as_view(), name='index_ans4'),
    url(r'^answered-5/$', views.Question5AnsListView.as_view(), name='index_ans5'),
    url(r'^answered-6/$', views.Question6AnsListView.as_view(), name='index_ans6'),
    url(r'^answered-7/$', views.Question7AnsListView.as_view(), name='index_ans7'),
    url(r'^answered-8/$', views.Question8AnsListView.as_view(), name='index_ans8'),
    url(r'^indexed/$', views.QuestionsIndexListView.as_view(), name='index_all'),
    url(r'^indexed-2/$', views.Questions2IndexListView.as_view(), name='index_all2'),
    url(r'^indexed-3/$', views.Questions3IndexListView.as_view(), name='index_all3'),
    url(r'^indexed-4/$', views.Questions4IndexListView.as_view(), name='index_all4'),
    url(r'^indexed-5/$', views.Questions5IndexListView.as_view(), name='index_all5'),
    url(r'^indexed-6/$', views.Questions6IndexListView.as_view(), name='index_all6'),
    url(r'^indexed-7/$', views.Questions7IndexListView.as_view(), name='index_all7'),
    url(r'^indexed-8/$', views.Questions8IndexListView.as_view(), name='index_all8'),
    url(r'^question-detail/(?P<pk>\d+)/$', views.QuestionDetailView.as_view(), name='question_detail'),
    url(r'^question-detail-2/(?P<pk>\d+)/$', views.Question2DetailView.as_view(), name='question_detail2'),
    url(r'^question-detail-3/(?P<pk>\d+)/$', views.Question3DetailView.as_view(), name='question_detail3'),
    url(r'^question-detail-4/(?P<pk>\d+)/$', views.Question4DetailView.as_view(), name='question_detail4'),
    url(r'^question-detail-5/(?P<pk>\d+)/$', views.Question5DetailView.as_view(), name='question_detail5'),
    url(r'^question-detail-6/(?P<pk>\d+)/$', views.Question6DetailView.as_view(), name='question_detail6'),
    url(r'^question-detail-7/(?P<pk>\d+)/$', views.Question7DetailView.as_view(), name='question_detail7'),
    url(r'^question-detail-8/(?P<pk>\d+)/$', views.Question8DetailView.as_view(), name='question_detail8'),
    url(r'^ask-question/$', views.CreateQuestionView.as_view(), name='ask_question'),
    url(r'^ask-question-2/$', views.CreateQuestion2View.as_view(), name='ask_question2'),
    url(r'^ask-question-3/$', views.CreateQuestion3View.as_view(), name='ask_question3'),
    url(r'^ask-question-4/$', views.CreateQuestion4View.as_view(), name='ask_question4'),
    url(r'^ask-question-5/$', views.CreateQuestion5View.as_view(), name='ask_question5'),
    url(r'^ask-question-6/$', views.CreateQuestion6View.as_view(), name='ask_question6'),
    url(r'^ask-question-7/$', views.CreateQuestion7View.as_view(), name='ask_question7'),
    url(r'^ask-question-8/$', views.CreateQuestion8View.as_view(), name='ask_question8'),
    url(r'^propose-answer/(?P<question_id>\d+)/$', views.CreateAnswerView.as_view(), name='propose_answer'),
    url(r'^propose-answer-2/(?P<question_id>\d+)/$', views.CreateAnswer2View.as_view(), name='propose_answer2'),
    url(r'^propose-answer-3/(?P<question_id>\d+)/$', views.CreateAnswer3View.as_view(), name='propose_answer3'),
    url(r'^propose-answer-4/(?P<question_id>\d+)/$', views.CreateAnswer4View.as_view(), name='propose_answer4'),
    url(r'^propose-answer-5/(?P<question_id>\d+)/$', views.CreateAnswer5View.as_view(), name='propose_answer5'),
    url(r'^propose-answer-6/(?P<question_id>\d+)/$', views.CreateAnswer6View.as_view(), name='propose_answer6'),
    url(r'^propose-answer-7/(?P<question_id>\d+)/$', views.CreateAnswer7View.as_view(), name='propose_answer7'),
    url(r'^propose-answer-8/(?P<question_id>\d+)/$', views.CreateAnswer8View.as_view(), name='propose_answer8'),
    url(r'^question/vote/$', views.question_vote, name='question_vote'),
    url(r'^question/vote-2/$', views.question_vote2, name='question_vote2'),
    url(r'^question/vote-3/$', views.question_vote3, name='question_vote3'),
    url(r'^question/vote-4/$', views.question_vote4, name='question_vote4'),
    url(r'^question/vote-5/$', views.question_vote5, name='question_vote5'),
    url(r'^question/vote-6/$', views.question_vote6, name='question_vote6'),
    url(r'^question/vote-7/$', views.question_vote7, name='question_vote7'),
    url(r'^question/vote-8/$', views.question_vote8, name='question_vote8'),
    url(r'^answer/vote/$', views.answer_vote, name='answer_vote'),
    url(r'^answer/vote-2/$', views.answer_vote2, name='answer_vote2'),
    url(r'^answer/vote-3/$', views.answer_vote3, name='answer_vote3'),
    url(r'^answer/vote-4/$', views.answer_vote4, name='answer_vote4'),
    url(r'^answer/vote-5/$', views.answer_vote5, name='answer_vote5'),
    url(r'^answer/vote-6/$', views.answer_vote6, name='answer_vote6'),
    url(r'^answer/vote-7/$', views.answer_vote7, name='answer_vote7'),
    url(r'^answer/vote-8/$', views.answer_vote8, name='answer_vote8'),
    url(r'^accept-answer/$', views.accept_answer, name='accept_answer'),
    url(r'^accept-answer-2/$', views.accept_answer2, name='accept_answer2'),
    url(r'^accept-answer-3/$', views.accept_answer3, name='accept_answer3'),
    url(r'^accept-answer-4/$', views.accept_answer4, name='accept_answer4'),
    url(r'^accept-answer-5/$', views.accept_answer5, name='accept_answer5'),
    url(r'^accept-answer-6/$', views.accept_answer6, name='accept_answer6'),
    url(r'^accept-answer-7/$', views.accept_answer7, name='accept_answer7'),
    url(r'^accept-answer-8/$', views.accept_answer8, name='accept_answer8'),
]

bootcamp/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from graphene_django.views import GraphQLView

urlpatterns = [
    url(r'^$',
        TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'), name='about'),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    # User management
    url(r'^users/', include('bootcamp.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),
    # Third party apps here
    url(r'^comments/', include('django_comments.urls')),
    url(r'^graphql', GraphQLView.as_view(graphiql=True)),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^invitations/', include('invitations.urls', namespace='invitations')),
    # Local apps here
    url(r'^notifications/',
        include('bootcamp.notifications.urls', namespace='notifications')),
    url(r'^articles/',
        include('bootcamp.articles.urls', namespace='articles')),
    url(r'^news/', include('bootcamp.news.urls', namespace='news')),
    url(r'^messages/',
        include('bootcamp.messager.urls', namespace='messager')),
    url(r'^qa/', include('bootcamp.qa.urls', namespace='qa')),
    url(r'^search/', include('bootcamp.search.urls', namespace='search')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

bootcamp/articles/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from hitcount.views import HitCountDetailView

from bootcamp.helpers import AuthorRequiredMixin
from bootcamp.articles.models import Article
from bootcamp.articles.forms import ArticleForm


class ArticlesListView(LoginRequiredMixin, ListView):
    """Basic ListView implementation to call the published articles list."""
    model = Article
    paginate_by = 15
    context_object_name = "articles"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['popular_tags'] = Article.objects.get_counted_tags()
        return context

    def get_queryset(self, **kwargs):
        return Article.objects.get_published()


class DraftsListView(ArticlesListView):
    """Overriding the original implementation to call the drafts articles
    list."""
    def get_queryset(self, **kwargs):
        return Article.objects.get_drafts()


class CreateArticleView(LoginRequiredMixin, CreateView):
    """Basic CreateView implementation to create new articles."""
    model = Article
    message = _("Ваш артикль был создан.")
    form_class = ArticleForm
    template_name = 'articles/article_create.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse('articles:list')


class EditArticleView(LoginRequiredMixin, AuthorRequiredMixin, UpdateView):
    """Basic EditView implementation to edit existing articles."""
    model = Article
    message = _("Ваш артикль был изменен.")
    form_class = ArticleForm
    template_name = 'articles/article_update.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse('articles:list')


class DetailArticleView(LoginRequiredMixin, HitCountDetailView):
    """Basic DetailView implementation to call an individual article."""
    model = Article
    count_hit = True

bootcamp/messager/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import render
from django.views.generic import ListView

from bootcamp.messager.models import Message
from bootcamp.helpers import ajax_required


class MessagesListView(LoginRequiredMixin, ListView):
    """CBV to render the inbox, showing by default the most recent
    conversation as the active one.
    """
    model = Message
    paginate_by = 50
    template_name = "messager/message_list.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['users_list'] = get_user_model().objects.filter(
            is_active=True).exclude(
                username=self.request.user).order_by('username')
        last_conversation = Message.objects.get_most_recent_conversation(
            self.request.user
        )
        context['active'] = last_conversation.username
        return context

    def get_queryset(self):
        active_user = Message.objects.get_most_recent_conversation(
            self.request.user)
        return Message.objects.get_conversation(active_user, self.request.user)


class ConversationListView(MessagesListView):
    """CBV to render the inbox, showing an specific conversation with a given
    user, who requires to be active too."""
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['active'] = self.kwargs["username"]
        return context

    def get_queryset(self):
        active_user = get_user_model().objects.get(
            username=self.kwargs["username"])
        return Message.objects.get_conversation(active_user, self.request.user)


@login_required
@ajax_required
def send_message(request):
    """AJAX Functional view to recieve just the minimum information, process
    and create the new message and return the new data to be attached to the
    conversation stream."""
    if request.method == 'POST':
        sender = request.user
        recipient_username = request.POST.get('to')
        recipient = get_user_model().objects.get(username=recipient_username)
        message = request.POST.get('message')
        if len(message.strip()) == 0:
            return HttpResponse()

        if sender != recipient:
            msg = Message.send_message(sender, recipient, message)
            return render(request, 'messager/single_message.html',
                          {'message': msg})

        return HttpResponse()

    else:
        return HttpResponseBadRequest()


@login_required
@ajax_required
def receive_message(request):
    """Simple AJAX functional view to return a rendered single message on the
    receiver side providing realtime connections."""
    if request.method == 'GET':
        message_id = request.GET.get('message_id')
        message = Message.objects.get(pk=message_id)
        return render(request,
                      'messager/single_message.html', {'message': message})

    else:
        return HttpResponseBadRequest()

bootcamp/users/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, ListView, RedirectView, UpdateView

from .models import User


class UserDetailView(LoginRequiredMixin, DetailView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'


class UserRedirectView(LoginRequiredMixin, RedirectView):
    permanent = False

    def get_redirect_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})


class UserUpdateView(LoginRequiredMixin, UpdateView):
    fields = ['name', 'email', 'picture', 'job_title', 'region', 'city', 'location', 'business_type', 'personal_url', 'short_bio', 'bio', 'phone_number',]
    model = User

    # send the user back to their own page after a successful update
    def get_success_url(self):
        return reverse('users:detail',
                       kwargs={'username': self.request.user.username})

    def get_object(self):
        # Only get the User record for the user making the request
        return User.objects.get(username=self.request.user.username)


class UserListView(LoginRequiredMixin, ListView):
    model = User
    # These next two lines tell the view to index lookups by username
    slug_field = 'username'
    slug_url_kwarg = 'username'

bootcamp/templates/articles/article_create.html
{% extends 'base.html' %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock head %}

{% block content %}

<!--   <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'articles:list' %}" style="color:#004a7a">{% trans 'Лента' %}</a></li>
      <li class="breadcrumb-item active" aria-current="page" style="color:#004a7a; opacity: 0.8;">{% trans 'Публикация' %}</li>
    </ol>
  </nav> -->
<div class="card" style="padding:10px; box-shadow: 0 0 10px rgba(0,0,0,0.5);margin-right: auto;margin-left: auto;margin-top:10px">
  <form action="{% url 'articles:write_new' %}" enctype="multipart/form-data"  id="article-form" method="post" role="form">

    <h1 style="text-align: center;">Публикация статьи</h1><hr>
    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-group">
      <button type="button" class="btn btn-primary publish" style="background-color: #004a7a"> <i class="fa fa-reply" aria-hidden="true"></i> {% trans 'Опубликовать' %}</button>
      <button type="button" class="btn btn-default draft"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> {% trans 'Сохранить как черновик' %}</button>
      <a href="{% url 'articles:list' %}" class="btn btn-default">{% trans 'Отмена' %}</a>
    </div>
  </form>
</div>
  {{ form.media }}

{% endblock content %}

{% block modal %}
  <script src="{% static 'js/articles.js' %}"></script>
{% endblock modal %}

bootcamp/templates/articles/article_detail.html
{% extends 'base.html' %}
{% load static i18n %}
{% load comments crispy_forms_tags thumbnail humanize %}
{% load hitcount_tags %}


{% block title %}{{ article.title|title }}{% endblock %}

{% block content %}
  <!-- Page Content -->
  <div class="container">
   <!--  <nav aria-label="breadcrumb">
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'articles:list' %}" style="color:#004a7a;font-size:1.5rem">{% trans 'Лента' %}</a></li>
        <li class="breadcrumb-item active" aria-current="page" style="color:#004a7a;font-size:1.5rem;opacity: 0.8;">{{ article.title|title }}</li>
      </ol>
    </nav> -->
    <div class="row" >
      <!-- Post Content Column -->
      <div class="col-lg-8">
        <!-- Title -->
        <h2 class="mt-4" id="titleArticle" style=" text-transform:uppercase;text-align: center;"> {{ article.title|title }}</h2>
        <hr>
        <!-- Author -->

        <i class="lead fa fa-user"></i>
          <a href="{% url 'users:detail' article.user.username %}"> {{ article.user.get_profile_name|title }}</a>
&nbsp;|&nbsp;&nbsp;<i class="lead fa fa-clock-o"></i>  {{ article.timestamp|date:'d.m.Y, G:i '  }}
         |&nbsp;&nbsp;<i class="lead fa fa-eye"></i> {% get_hit_count for article %}
        <hr>
        <!-- Featured Image -->
        {% thumbnail article.image "900x300" as im %}
          <img src="{{ im.url }}" alt="{% trans 'Загруженное фото' %}" class="card-img-top">
        {% empty %}
          <img class="img-fluid rounded" src="http://placehold.it/900x300" alt="Фото карточки">
        {% endthumbnail %}
        <!-- <img src="{{ MEDIA_URL }}{{ article.image }}" lt="{% trans 'Картинка статьи' %}" class="card-img-top"> -->
        <hr>
        <!-- Post Content -->
        <p class="card-text">{{ article.get_markdown|safe }}</p>
        <hr>
            {% if article.file %}
                <p style="font-size:1.2rem">   <b>Прикрепленный файл:</b>  <span class="fa fa-folder" style="color:#ffb100"></span> <a href="{{ article.file.url }}">{{ article.filename }}</a></p>
            {% endif %}
        <hr>

        <p>Ссылка на соответствующее обсуждение: <a href="http://localhost:8000/qa/question-detail-7/1/">Нажмите чтобы обсудить</a></p>
        <hr>
        <!-- Comments Form -->
        <div class="card my-4">
          <h5 class="card-header">{% trans 'Оставить комментарий' %}:</h5>
          <div class="card-body">
            {% if user.is_authenticated %}
              {% get_comment_form for article as form %}
              <form action="{% comment_form_target %}" method="POST">
                {% csrf_token %}
                {{ form|crispy }}
                <input type="hidden" name="next" value="{% url 'articles:article' article.slug %}" />
                <input type="submit" value="{% trans 'Прокомментировать' %}" id="id_submit" />
              </form>
            {% endif %}
          </div>
        </div>

        <!-- Single Comment -->

        {% get_comment_list for article as comment_list %}
        {% for comment in comment_list %}
          <div class="media mb-4">
            {% thumbnail comment.user.picture "x50" as im %}
              <img class="d-flex mr-3 rounded-circle" src="{{ im.url }}" alt="{% trans 'Фото профиля' %}" id="pic" />
            {% empty %}
              <img class="d-flex mr-3 rounded-circle" src="{% static 'img/user.png' %}" height="50px" alt="{% trans 'Нет фото профиля' %}" />
            {% endthumbnail %}
            <div class="media-body">
              <h5 class="mt-0">{{ comment.user.get_profile_name|title }}</h5>
              {{ comment }}
            </div>
          </div>
        {% endfor %}
      </div>

      <!-- Sidebar Widgets Column -->
      <div class="col-md-4">

        <!-- Write Article Widget -->
        <!-- {% if request.user.is_authenticated %}
          <div class="card my-4">
            <div class="card-body text-center">
              <a class="btn btn-success" href="{% url 'articles:write_new' %}" title="{% trans 'Написать новый блог' %}"><i class="fa fa-pencil" aria-hidden="true"></i> {% trans 'Новый блог' %}</a>
              <a class="btn btn-primary" href="{% url 'articles:edit_article' article.id %}" title="{% trans 'Изменить блог' %}"><i class="fa fa-pencil-square-o" aria-hidden="true"></i> {% trans 'Изменить' %}</a>
            </div>
          </div>
        {% endif %} -->
        <!-- Cloud Tag Widget -->
        <div class="card my-4">
          <h5 class="card-header">{% trans 'Хэштеги' %}</h5>
          <div class="card-body">
            {% for tag in article.tags.all %}
              <a href="#"><span class="badge badge-info">{{ tag }}</span></a>
            {% endfor %}
          </div>
        </div>
      </div>
    </div>
    <!-- /.row -->
  </div>
  <style type="text/css">

  </style>
  <!-- /.container -->
{% endblock content %}

bootcamp/templates/articles/article_update.html
{% extends 'base.html' %}
{% load static i18n %}
{% load crispy_forms_tags %}

{% block head %}
{% endblock head %}

{% block content %}

  <nav aria-label="breadcrumb">
    <ol class="breadcrumb">
      <li class="breadcrumb-item"><a href="{% url 'news:list' %}">{% trans 'Домой' %}</a></li>
      <li class="breadcrumb-item"><a href="{% url 'articles:drafts' %}">{% trans 'Черновики' %}</a></li>
      <li class="breadcrumb-item active" aria-current="page">{% trans 'Обновить блог' %}</li>
    </ol>
  </nav>
  <form action="{% url 'articles:edit_article' form.instance.pk %}" enctype="multipart/form-data"  id="article-form" method="post" role="form">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="form-group">
      <button type="button" class="btn btn-primary update">{% trans 'Обновить' %}</button>
      <button type="button" class="btn btn-default draft">{% trans 'Сохранить как черновик' %}</button>
      <a href="{% url 'articles:drafts' %}" class="btn btn-default">{% trans 'Отмена' %}</a>
    </div>
  </form>
  {{ form.media }}

{% endblock content %}

{% block modal %}
  <script src="{% static 'js/articles.js' %}"></script>
{% endblock modal %}