bootcamp/messager/urls.py
from django.conf.urls import url

from bootcamp.messager import views

app_name = 'messager'
urlpatterns = [
    url(r'^$', views.MessagesListView.as_view(), name='messages_list'),
    url(r'^send-message/$', views.send_message, name='send_message'),
    url(r'^receive-message/$',
        views.receive_message, name='receive_message'),
    url(r'^(?P<username>[\w.@+-]+)/$', views.ConversationListView.as_view(),
        name='conversation_detail'),
]

bootcamp/news/urls.py
from django.conf.urls import url

from bootcamp.news import views

app_name = 'news'
urlpatterns = [
    url(r'^$', views.NewsListView.as_view(), name='list'),
    url(r'^delete/(?P<pk>[-\w]+)/$',
        views.NewsDeleteView.as_view(), name='delete_news'),
    url(r'^post-news/$', views.post_news, name='post_news'),
    url(r'^like/$', views.like, name='like_post'),
    url(r'^dislike/$', views.dislike, name='dislike_post'),
    url(r'^get-thread/$', views.get_thread, name='get_thread'),
    url(r'^post-comment/$', views.post_comment, name='post_comments'),
    url(r'^update-interactions/$', views.update_interactions, name='update_interactions'),
    url(r'^news-table/$', views.tablify, name='tablify'),
]

bootcamp/qa/urls.py
from django.conf.urls import url

from bootcamp.qa import views

app_name = 'qa'
urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='question_main'),
    url(r'^main/$', views.FakeIndexView.as_view(), name='question_fake_main'),
    url(r'^question-list/$', views.QuestionListView.as_view(), name='index_noans'),
    url(r'^question-list-2/$', views.Question2ListView.as_view(), name='index_noans2'),
    url(r'^question-list-3/$', views.Question3ListView.as_view(), name='index_noans3'),
    url(r'^question-list-4/$', views.Question4ListView.as_view(), name='index_noans4'),
    url(r'^question-list-5/$', views.Question5ListView.as_view(), name='index_noans5'),
    url(r'^question-list-6/$', views.Question6ListView.as_view(), name='index_noans6'),
    url(r'^question-list-7/$', views.Question7ListView.as_view(), name='index_noans7'),
    url(r'^question-list-8/$', views.Question8ListView.as_view(), name='index_noans8'),
    url(r'^answered/$', views.QuestionAnsListView.as_view(), name='index_ans'),
    url(r'^answered-2/$', views.Question2AnsListView.as_view(), name='index_ans2'),
    url(r'^answered-3/$', views.Question3AnsListView.as_view(), name='index_ans3'),
    url(r'^answered-4/$', views.Question4AnsListView.as_view(), name='index_ans4'),
    url(r'^answered-5/$', views.Question5AnsListView.as_view(), name='index_ans5'),
    url(r'^answered-6/$', views.Question6AnsListView.as_view(), name='index_ans6'),
    url(r'^answered-7/$', views.Question7AnsListView.as_view(), name='index_ans7'),
    url(r'^answered-8/$', views.Question8AnsListView.as_view(), name='index_ans8'),
    url(r'^indexed/$', views.QuestionsIndexListView.as_view(), name='index_all'),
    url(r'^indexed-2/$', views.Questions2IndexListView.as_view(), name='index_all2'),
    url(r'^indexed-3/$', views.Questions3IndexListView.as_view(), name='index_all3'),
    url(r'^indexed-4/$', views.Questions4IndexListView.as_view(), name='index_all4'),
    url(r'^indexed-5/$', views.Questions5IndexListView.as_view(), name='index_all5'),
    url(r'^indexed-6/$', views.Questions6IndexListView.as_view(), name='index_all6'),
    url(r'^indexed-7/$', views.Questions7IndexListView.as_view(), name='index_all7'),
    url(r'^indexed-8/$', views.Questions8IndexListView.as_view(), name='index_all8'),
    url(r'^question-detail/(?P<pk>\d+)/$', views.QuestionDetailView.as_view(), name='question_detail'),
    url(r'^question-detail-2/(?P<pk>\d+)/$', views.Question2DetailView.as_view(), name='question_detail2'),
    url(r'^question-detail-3/(?P<pk>\d+)/$', views.Question3DetailView.as_view(), name='question_detail3'),
    url(r'^question-detail-4/(?P<pk>\d+)/$', views.Question4DetailView.as_view(), name='question_detail4'),
    url(r'^question-detail-5/(?P<pk>\d+)/$', views.Question5DetailView.as_view(), name='question_detail5'),
    url(r'^question-detail-6/(?P<pk>\d+)/$', views.Question6DetailView.as_view(), name='question_detail6'),
    url(r'^question-detail-7/(?P<pk>\d+)/$', views.Question7DetailView.as_view(), name='question_detail7'),
    url(r'^question-detail-8/(?P<pk>\d+)/$', views.Question8DetailView.as_view(), name='question_detail8'),
    url(r'^ask-question/$', views.CreateQuestionView.as_view(), name='ask_question'),
    url(r'^ask-question-2/$', views.CreateQuestion2View.as_view(), name='ask_question2'),
    url(r'^ask-question-3/$', views.CreateQuestion3View.as_view(), name='ask_question3'),
    url(r'^ask-question-4/$', views.CreateQuestion4View.as_view(), name='ask_question4'),
    url(r'^ask-question-5/$', views.CreateQuestion5View.as_view(), name='ask_question5'),
    url(r'^ask-question-6/$', views.CreateQuestion6View.as_view(), name='ask_question6'),
    url(r'^ask-question-7/$', views.CreateQuestion7View.as_view(), name='ask_question7'),
    url(r'^ask-question-8/$', views.CreateQuestion8View.as_view(), name='ask_question8'),
    url(r'^propose-answer/(?P<question_id>\d+)/$', views.CreateAnswerView.as_view(), name='propose_answer'),
    url(r'^propose-answer-2/(?P<question_id>\d+)/$', views.CreateAnswer2View.as_view(), name='propose_answer2'),
    url(r'^propose-answer-3/(?P<question_id>\d+)/$', views.CreateAnswer3View.as_view(), name='propose_answer3'),
    url(r'^propose-answer-4/(?P<question_id>\d+)/$', views.CreateAnswer4View.as_view(), name='propose_answer4'),
    url(r'^propose-answer-5/(?P<question_id>\d+)/$', views.CreateAnswer5View.as_view(), name='propose_answer5'),
    url(r'^propose-answer-6/(?P<question_id>\d+)/$', views.CreateAnswer6View.as_view(), name='propose_answer6'),
    url(r'^propose-answer-7/(?P<question_id>\d+)/$', views.CreateAnswer7View.as_view(), name='propose_answer7'),
    url(r'^propose-answer-8/(?P<question_id>\d+)/$', views.CreateAnswer8View.as_view(), name='propose_answer8'),
    url(r'^question/vote/$', views.question_vote, name='question_vote'),
    url(r'^question/vote-2/$', views.question_vote2, name='question_vote2'),
    url(r'^question/vote-3/$', views.question_vote3, name='question_vote3'),
    url(r'^question/vote-4/$', views.question_vote4, name='question_vote4'),
    url(r'^question/vote-5/$', views.question_vote5, name='question_vote5'),
    url(r'^question/vote-6/$', views.question_vote6, name='question_vote6'),
    url(r'^question/vote-7/$', views.question_vote7, name='question_vote7'),
    url(r'^question/vote-8/$', views.question_vote8, name='question_vote8'),
    url(r'^answer/vote/$', views.answer_vote, name='answer_vote'),
    url(r'^answer/vote-2/$', views.answer_vote2, name='answer_vote2'),
    url(r'^answer/vote-3/$', views.answer_vote3, name='answer_vote3'),
    url(r'^answer/vote-4/$', views.answer_vote4, name='answer_vote4'),
    url(r'^answer/vote-5/$', views.answer_vote5, name='answer_vote5'),
    url(r'^answer/vote-6/$', views.answer_vote6, name='answer_vote6'),
    url(r'^answer/vote-7/$', views.answer_vote7, name='answer_vote7'),
    url(r'^answer/vote-8/$', views.answer_vote8, name='answer_vote8'),
    url(r'^accept-answer/$', views.accept_answer, name='accept_answer'),
    url(r'^accept-answer-2/$', views.accept_answer2, name='accept_answer2'),
    url(r'^accept-answer-3/$', views.accept_answer3, name='accept_answer3'),
    url(r'^accept-answer-4/$', views.accept_answer4, name='accept_answer4'),
    url(r'^accept-answer-5/$', views.accept_answer5, name='accept_answer5'),
    url(r'^accept-answer-6/$', views.accept_answer6, name='accept_answer6'),
    url(r'^accept-answer-7/$', views.accept_answer7, name='accept_answer7'),
    url(r'^accept-answer-8/$', views.accept_answer8, name='accept_answer8'),
]

bootcamp/search/urls.py
from django.conf.urls import url

from bootcamp.search import views

app_name = 'search'
urlpatterns = [
    url(r'^$', views.SearchListView.as_view(), name='results'),
    url(r'^suggestions/$', views.get_suggestions, name='suggestions'),
]

bootcamp/users/urls.py
from django.conf.urls import url

from . import views

app_name = 'users'
urlpatterns = [
    url(
        regex=r'^$',
        view=views.UserListView.as_view(),
        name='list'
    ),
    url(
        regex=r'^~redirect/$',
        view=views.UserRedirectView.as_view(),
        name='redirect'
    ),
    url(
        regex=r'^~update/$',
        view=views.UserUpdateView.as_view(),
        name='update'
    ),
    url(
        regex=r'^(?P<username>[\w.@+-]+)/$',
        view=views.UserDetailView.as_view(),
        name='detail'
    ),
]

config/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

from graphene_django.views import GraphQLView

urlpatterns = [
    url(r'^$',
        TemplateView.as_view(template_name='pages/home.html'), name='home'),
    url(r'^about/$',
        TemplateView.as_view(template_name='pages/about.html'), name='about'),
    # Django Admin, use {% url 'admin:index' %}
    url(settings.ADMIN_URL, admin.site.urls),
    # User management
    url(r'^users/', include('bootcamp.users.urls', namespace='users')),
    url(r'^accounts/', include('allauth.urls')),
    # Third party apps here
    url(r'^comments/', include('django_comments.urls')),
    url(r'^graphql', GraphQLView.as_view(graphiql=True)),
    url(r'^markdownx/', include('markdownx.urls')),
    url(r'^invitations/', include('invitations.urls', namespace='invitations')),
    # Local apps here
    url(r'^notifications/',
        include('bootcamp.notifications.urls', namespace='notifications')),
    url(r'^articles/',
        include('bootcamp.articles.urls', namespace='articles')),
    url(r'^news/', include('bootcamp.news.urls', namespace='news')),
    url(r'^messages/',
        include('bootcamp.messager.urls', namespace='messager')),
    url(r'^qa/', include('bootcamp.qa.urls', namespace='qa')),
    url(r'^search/', include('bootcamp.search.urls', namespace='search')),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development
    urlpatterns += [
        url(r'^400/$', default_views.bad_request, kwargs={'exception': Exception('Bad Request!')}),
        url(r'^403/$', default_views.permission_denied, kwargs={'exception': Exception('Permission Denied')}),
        url(r'^404/$', default_views.page_not_found, kwargs={'exception': Exception('Page not Found')}),
        url(r'^500/$', default_views.server_error),
    ]
    if 'debug_toolbar' in settings.INSTALLED_APPS:
        import debug_toolbar
        urlpatterns = [
            url(r'^__debug__/', include(debug_toolbar.urls)),
        ] + urlpatterns

bootcamp/articles/forms.py
from django import forms

from markdownx.fields import MarkdownxFormField

from bootcamp.articles.models import Article


class ArticleForm(forms.ModelForm):
    status = forms.CharField(widget=forms.HiddenInput())
    edited = forms.BooleanField(
        widget=forms.HiddenInput(), required=False, initial=False)
    # content = MarkdownxFormField()

    class Meta:
        model = Article
        fields = ["title", "content", "image", "tags", "status", "edited", "file"]

bootcamp/articles/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _
from hitcount.views import HitCountDetailView

from bootcamp.helpers import AuthorRequiredMixin
from bootcamp.articles.models import Article
from bootcamp.articles.forms import ArticleForm


class ArticlesListView(LoginRequiredMixin, ListView):
    """Basic ListView implementation to call the published articles list."""
    model = Article
    paginate_by = 15
    context_object_name = "articles"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['popular_tags'] = Article.objects.get_counted_tags()
        return context

    def get_queryset(self, **kwargs):
        return Article.objects.get_published()


class DraftsListView(ArticlesListView):
    """Overriding the original implementation to call the drafts articles
    list."""
    def get_queryset(self, **kwargs):
        return Article.objects.get_drafts()


class CreateArticleView(LoginRequiredMixin, CreateView):
    """Basic CreateView implementation to create new articles."""
    model = Article
    message = _("Ваш артикль был создан.")
    form_class = ArticleForm
    template_name = 'articles/article_create.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse('articles:list')


class EditArticleView(LoginRequiredMixin, AuthorRequiredMixin, UpdateView):
    """Basic EditView implementation to edit existing articles."""
    model = Article
    message = _("Ваш артикль был изменен.")
    form_class = ArticleForm
    template_name = 'articles/article_update.html'

    def form_valid(self, form):
        form.instance.user = self.request.user
        return super().form_valid(form)

    def get_success_url(self):
        messages.success(self.request, self.message)
        return reverse('articles:list')


class DetailArticleView(LoginRequiredMixin, HitCountDetailView):
    """Basic DetailView implementation to call an individual article."""
    model = Article
    count_hit = True

bootcamp/messager/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseBadRequest
from django.shortcuts import render
from django.views.generic import ListView

from bootcamp.messager.models import Message
from bootcamp.helpers import ajax_required


class MessagesListView(LoginRequiredMixin, ListView):
    """CBV to render the inbox, showing by default the most recent
    conversation as the active one.
    """
    model = Message
    paginate_by = 50
    template_name = "messager/message_list.html"

    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['users_list'] = get_user_model().objects.filter(
            is_active=True).exclude(
                username=self.request.user).order_by('username')
        last_conversation = Message.objects.get_most_recent_conversation(
            self.request.user
        )
        context['active'] = last_conversation.username
        return context

    def get_queryset(self):
        active_user = Message.objects.get_most_recent_conversation(
            self.request.user)
        return Message.objects.get_conversation(active_user, self.request.user)


class ConversationListView(MessagesListView):
    """CBV to render the inbox, showing an specific conversation with a given
    user, who requires to be active too."""
    def get_context_data(self, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        context['active'] = self.kwargs["username"]
        return context

    def get_queryset(self):
        active_user = get_user_model().objects.get(
            username=self.kwargs["username"])
        return Message.objects.get_conversation(active_user, self.request.user)


@login_required
@ajax_required
def send_message(request):
    """AJAX Functional view to recieve just the minimum information, process
    and create the new message and return the new data to be attached to the
    conversation stream."""
    if request.method == 'POST':
        sender = request.user
        recipient_username = request.POST.get('to')
        recipient = get_user_model().objects.get(username=recipient_username)
        message = request.POST.get('message')
        if len(message.strip()) == 0:
            return HttpResponse()

        if sender != recipient:
            msg = Message.send_message(sender, recipient, message)
            return render(request, 'messager/single_message.html',
                          {'message': msg})

        return HttpResponse()

    else:
        return HttpResponseBadRequest()


@login_required
@ajax_required
def receive_message(request):
    """Simple AJAX functional view to return a rendered single message on the
    receiver side providing realtime connections."""
    if request.method == 'GET':
        message_id = request.GET.get('message_id')
        message = Message.objects.get(pk=message_id)
        return render(request,
                      'messager/single_message.html', {'message': message})

    else:
        return HttpResponseBadRequest()

bootcamp/templates/403_csrf.html
{% extends "base.html" %}

{% block title %}Forbidden (403){% endblock %}

{% block content %}
<h1>Forbidden (403)</h1>

<p>CSRF verification failed. Request aborted.</p>
{% endblock content %}

bootcamp/templates/base.html
{% load static i18n thumbnail %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Atameken Online{% endblock title %}</title>
    <link rel="icon" type="image/png" href="{% static 'img/atahome.png' %}">
    <meta name="description" content="An Enterprise Social Network">
    <meta name="author" content="AT">
    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->
    {% block css %}
    <!-- Latest compiled and minified Bootstrap 4 beta CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Your stuff: Third-party CSS libraries go here -->
    <link rel="stylesheet" type="text/css" href="{% static 'fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
    <!-- This file stores project-specific CSS -->
    <link href="{% static 'css/bootcamp.css' %}?v=1" rel="stylesheet">
    {% endblock css %}
    {% block head %}{% endblock head %}
  </head>

  <body>
    {% block body %}
      <div class="m-b-1">
        {% if request.user.is_authenticated %}
          <nav class="navbar fixed-top navbar-expand-md navbar-dark" style="background-color: white; box-shadow: 0 0 10px rgba(0,0,0,0.5);">
            <div class="container">
              <div style="display: flex">
                <div>
                  <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation" style="">
                  <span class="fa fa-navicon" style="color: #004a7a;"></span>
                  </button>
                </div>

                <div>
                  <a class="navbar-brand" href="{% url 'articles:list' %}" style="color: #004a7a;" id="company">
                    <img src="https://pbs.twimg.com/profile_images/514398182051041280/0Bxydy03.png" width="30" height="30" class="d-inline-block align-top" alt="">
                    Atameken <font color="#ffb100">Online</font></a>
                </div>
              </div>

              <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <!--         <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="btn btn-md" href="#" id="notifications" data-toggle="popover" data-title="{% trans 'Notifications' %}">

                        <i class="fa fa-send-o" aria-hidden="true"></i>
                    </a>
                  </li>
                </ul>
 -->

                <ul class="navbar-nav">
                  <li class="nav-item">
                    <a class="btn btn-md new-nav-link btn-danger"  href="{% url 'messager:messages_list' %}" style="background-color: #dc3545;font-size: 1.5em;
  padding: 13px;
  color: #dddddd;">

                        <img src="{% static 'img/support.png' %}"  width="30" height="30" class="d-inline-block align-top" alt="">
                    </a>
                  </li>
                </ul>

                <ul class="menu navbar-nav mr-auto">
{#                  <li class="nav-item">#}
{#                    <a class="nav-link" href="{% url 'news:list' %}" style="color: #004a7a;">{% trans 'Новости' %} <span class="sr-only">(current)</span></a>#}
{#                  </li>#}
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'articles:list' %}" style="color: #004a7a;">Новостная лента</a>
                  </li>
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'qa:question_main' %}" style="color: #004a7a;">{% trans 'Обсуждения' %}</a>
                  </li>
            <!--       <li class="nav-item">
                    <a class="nav-link" href="{% url 'messager:messages_list' %}" style="color: #004a7a;">{% trans 'Чат' %}</a>
                  </li> -->
                  <li class="nav-item">
                    <a class="nav-link" href="{% url 'users:list' %}" style="color: #004a7a;">{% trans 'Компании' %}</a>
                  </li>
                </ul>


                <ul class="nav navbar-nav">
                  {% if not hide_search %}
                    <form class="form-inline navbar" role="search" action="{% url 'search:results' %}" id="searchCSS">
                      <div class="input-group">
                        <input name="query" type="search" id="searchInput" class="form-control" placeholder="{% trans 'Поиск' %}" aria-label="Search" >
                        <div class="input-group-append">
                          <span class="input-group-text"><i class="fa fa-search" aria-hidden="true"></i></span>
                        </div>
                      </div>
                    </form>
                  {% endif %}
                </ul>

               <ul class="navbar-nav">
                  <div class="row" style="white-space: nowrap" id="profileCSS">
                  <li class="nav-item dropdown" id="profileDrop">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: #004a7a;">
                      {% thumbnail request.user.picture "x30" as im %}
                        <img src="{{ im.url }}" style="border-radius: 50%;" alt="{% trans 'User Image' %}" class="user-image">
                      {% empty %}
                        <img src="{% static 'img/user.png' %}" height="30px" alt="{% trans 'No Profile Picture' %}" />
                      {% endthumbnail %}
                      {{ request.user.username }}
                    </a>

                     <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <a class="dropdown-item" href="{% url 'users:detail' request.user.username  %}">
                        <i class="fa fa-user" aria-hidden="true"></i>&nbsp; {% trans 'Профиль' %}</a>
                      <div class="dropdown-divider"></div>
                           <form class="dropdown-item"  method="post" action="{% url 'account_logout' %}">
                                {% csrf_token %}
                                {% if redirect_field_value %}
                                    <input type="hidden" name="{{ redirect_field_name }}" value="{{ redirect_field_value }}" />
                                {% endif %}
                                <i class="fa fa-sign-out fa-fw" aria-hidden="true"></i>&nbsp;
                                <button class="logout-btn" style="background-color: none;background: none; color: inherit; border: none; width:100%;height:80%;text-align:left;" type="submit">{% trans 'Выйти' %}</button>
                            </form>
                      </div>
                  </li>
                </div>
                </ul>
              </div>
            </div>
          </nav>
        {% endif %}
      </div>
      <div id="header" class="container">
        {% if messages %}
          {% for message in messages %}
            <div id="messages" class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">
              <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
              {{ message }}
            </div>
          {% endfor %}
        {% endif %}

        {% block content %}

        {% endblock content %}
      </div>


      <style>
      .menu .nav-link {
        text-decoration: none;
        position: relative;
        }

      @media (min-width: 768px) {
      .menu .nav-link:after {
        position: absolute;
        content: '';
        height: 2px;
        bottom: -4px;
        margin: 0 auto;
        left: 0;
        right: 0;
        width: 50%;
        -o-transition:.5s;
        -ms-transition:.5s;
        -moz-transition:.5s;
        -webkit-transition:.5s;
        transition:.5s;
      }

      .menu .nav-link:hover:after {
        width: 80%;
        background: #004a7a;
        }
      }
      .menu .new-nav-link {
        color: #ffb100 !important;
      }

      @media (max-width: 768px) {
        #company {
          margin-top: -5px;
          position: fixed;
          right: 0;
        }
        #searchCSS {
          margin-left:-15px;
        }
        #profileCSS {
          margin-left:3px;
        }
        #navbarSupportedContent {
          padding-top:15px;
        }
      }
      </style>

      <!-- /container -->

      <!-- Le javascript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      {% block javascript %}
        <!-- Required by Bootstrap v4 -->
        <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
        <!-- Your stuff: Third-party javascript libraries go here -->
        <script src="https://ajax.googleapis.com/ajax/libs/jqueryui/1.8.23/jquery-ui.min.js" type="text/javascript"></script>
        <!-- place project specific Javascript in this file -->
        <script src="{% static 'js/bootcamp.js' %}" type="text/javascript"></script>
        <script src="{% static 'channels/js/websocketbridge.js' %}" type="text/javascript"></script>
        <script type="text/javascript">
          var currentUser = "{{ request.user.username }}"
          $(function() {
                  source: "{% url 'search:suggestions' %}",
                  minLength: 2
              });
        </script>

        <script type="text/javascript">
          $(function() {
            $('nav a[href^="/' + location.pathname.split("/")[1] + '"]').addClass('new-nav-link').removeClass('menu');
        });
        </script>


      {% endblock javascript %}

      {% block modal %}{% endblock modal %}

    {% endblock body %}
  </body>
  <!-- /.container -->
</html>